---
apiVersion: v1
kind: Namespace
metadata:
  name: expensetracker
  labels:
    app.kubernetes.io/name: expensetracker
    app.kubernetes.io/managed-by: argocd
    name: expensetracker  # For network policy selector
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: expensetracker-quota
  namespace: expensetracker
  labels:
    app.kubernetes.io/name: expensetracker
    app.kubernetes.io/managed-by: argocd
spec:
  hard:
    # Compute resources
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    
    # Object counts
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
    
    # Storage
    requests.storage: "100Gi"
---
# Limit Range for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: expensetracker-limits
  namespace: expensetracker
  labels:
    app.kubernetes.io/name: expensetracker
    app.kubernetes.io/managed-by: argocd
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
      ephemeral-storage: "500Mi"
    max:
      cpu: "2"
      memory: "4Gi"
      ephemeral-storage: "5Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
      ephemeral-storage: "100Mi"
  - type: Pod
    max:
      cpu: "4"
      memory: "8Gi"
      ephemeral-storage: "10Gi"
  - type: PersistentVolumeClaim
    min:
      storage: "1Gi"
    max:
      storage: "50Gi"