services:
  # Development-specific overrides
  auth-service:
    develop:
      watch:
        - path: ../../Backend/AuthService
          action: rebuild
    volumes:
      - ../../Backend/AuthService/logs:/app/logs

  expense-service:
    develop:
      watch:
        - path: ../../Backend/ExpenseService
          action: rebuild
    volumes:
      - ../../Backend/ExpenseService/logs:/app/logs

  category-service:
    develop:
      watch:
        - path: ../../Backend/CategoryService
          action: rebuild
    volumes:
      - ../../Backend/CategoryService/logs:/app/logs

  budget-service:
    develop:
      watch:
        - path: ../../Backend/BudgetService
          action: rebuild
    volumes:
      - ../../Backend/BudgetService/logs:/app/logs

  savings-goal-service:
    develop:
      watch:
        - path: ../../Backend/SavingsGoalService
          action: rebuild
    volumes:
      - ../../Backend/SavingsGoalService/logs:/app/logs

  analytics-service:
    develop:
      watch:
        - path: ../../Backend/AnalyticsService
          action: rebuild
    volumes:
      - ../../Backend/AnalyticsService/logs:/app/logs

  # Development database with exposed ports for easier debugging
  postgres:
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
