/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetsIndexRouteImport } from './routes/budgets/index'

const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIndexRoute = BudgetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRouteWithChildren
  '/budgets/': typeof BudgetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRouteWithChildren
  '/budgets/': typeof BudgetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/budgets' | '/budgets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/budgets'
  id: '__root__' | '/' | '/budgets' | '/budgets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsRoute: typeof BudgetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/'
      fullPath: '/budgets/'
      preLoaderRoute: typeof BudgetsIndexRouteImport
      parentRoute: typeof BudgetsRoute
    }
  }
}

interface BudgetsRouteChildren {
  BudgetsIndexRoute: typeof BudgetsIndexRoute
}

const BudgetsRouteChildren: BudgetsRouteChildren = {
  BudgetsIndexRoute: BudgetsIndexRoute,
}

const BudgetsRouteWithChildren =
  BudgetsRoute._addFileChildren(BudgetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsRoute: BudgetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
