apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: expensetracker
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: expensetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expensetracker-secrets
                  key: DB_PASSWORD
            - name: MSSQL_PID
              value: "Express"
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: expensetracker
spec:
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
